import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeContext";
import { Toaster } from "react-hot-toast";

import { shadesOfPurple } from '@clerk/themes'
import ServiceWorkerInitializer from "./(root)/_components/ServiceWorkerInitializer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ZitaCode",
  description: "Generated by @sjx",
  manifest: "./manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme:  shadesOfPurple,
    }}
      >
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen
         bg-gradient-to-b from-gray-900 to-gray-950 text-gray-100 flex flex-col`}
        
      >
        <Toaster position="top-center" />
        <ThemeProvider>
        <ConvexClientProvider>
        <ServiceWorkerInitializer />
       {children}
      
       </ConvexClientProvider>
      
        <Footer />
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
